const BASE_URL = process.env.NEXT_PUBLIC_API_URL || ""



export async function getRawMaterials() {
  return [
    {
      id: 1,
      name: "Germall Plus",
      description: "Protects water-based skincare products from bacteria...",
      price: 5000,
      originalPrice: null,
      rating: 5,
      badge: null,
      image: "/images/germanPlus.png",
      category: "raw",
      slug: "germall-plus",
    },
    {
      id: 2,
      name: "Kojic Dipalmitate",
      description: "Skin whiteninglightening, sun ...",
      price: 60000,
      originalPrice: null,
      rating: 5,
      badge: null,
      image: "/images/kojic.png",
      category: "raw",
      slug: "niacinamide-powder",
    },
    {
      id: 3,
      name: "Vitamin E Oil",
      description: "Protects the skin from damage, kepps...",
      price: 3000,
      originalPrice: 5000,
      rating: 5,
      badge: "LIMITED",
      image: "/images/VitaminE.png",
      category: "raw",
      slug: "shea-butter",
    },
    {
      id: 4,
      name: "Kojic Acid",
      description: "Lightening agent for hyperpigmentation and dark spots...",
      price: 6000,
      originalPrice: null,
      rating: 5,
      badge: null,
      image: "/images/kojic.png",
      category: "raw",
      slug: "kojic-acid",
    },
    {
      id: 5,
      name: "Germall Plus",
      description: "Protects water-based skincare products from bacteria...",
      price: 5000,
      originalPrice: null,
      rating: 5,
      badge: null,
      image: "/images/germanPlus.png",
      category: "raw",
      slug: "germall-plus",
    },
    {
      id: 6,
      name: "Kojic Dipalmitate",
      description: "Skin whiteninglightening, sun ...",
      price: 60000,
      originalPrice: null,
      rating: 5,
      badge: null,
      image: "/images/kojic.png",
      category: "raw",
      slug: "niacinamide-powder",
    },
    {
      id: 7,
      name: "Vitamin E Oil",
      description: "Protects the skin from damage, kepps...",
      price: 3000,
      originalPrice: 5000,
      rating: 5,
      badge: "LIMITED",
      image: "/images/VitaminE.png",
      category: "raw",
      slug: "shea-butter",
    },
    {
      id: 8,
      name: "Kojic Acid",
      description: "Lightening agent for hyperpigmentation and dark spots...",
      price: 6000,
      originalPrice: null,
      rating: 5,
      badge: null,
      image: "/images/kojic.png",
      category: "raw",
      slug: "kojic-acid",
    },
  ]
}