# Generated by Django 6.0.3 on 2026-03-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ('state', 'city')},
        ),
        migrations.RenameField(
            model_name='deliveryzone',
            old_name='area',
            new_name='city',
        ),
        migrations.AlterUniqueTogether(
            name='deliveryzone',
            unique_together={('state', 'city')},
        ),
    ]
