# Generated by Django 6.0.3 on 2026-03-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_deliveryzone_options_and_more'),
    ]

    operations = [
    migrations.RunSQL(
        "UPDATE \"Products_productvariant\" SET stock = 0 WHERE stock IS NULL;",
        reverse_sql=migrations.RunSQL.noop
    ),
    migrations.RunSQL(
        "UPDATE \"Products_product\" SET stock = 0 WHERE stock IS NULL;",
        reverse_sql=migrations.RunSQL.noop
    ),
    migrations.RemoveField(
        model_name='product',
        name='stock',
    ),
    migrations.RemoveField(
        model_name='productvariant',
        name='stock',
    ),
]
