# Generated by Django 6.0.3 on 2026-03-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_deliveryzone_options_and_more'),
    ]

    operations = [
        # empty, or any safe operations unrelated to 'stock'
    ]