# Generated by Django 6.0.3 on 2026-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_remove_product_stock_remove_productvariant_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
