# Generated by Django 6.0.3 on 2026-04-07 17:15

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Product = apps.get_model('Products', 'Product')
    for product in Product.objects.only('pk', 'name', 'slug'):
        base_slug = slugify(product.name)
        slug = base_slug
        counter = 1
        while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        product.slug = slug
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_seed_delivery_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=False),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, blank=True),
        ),
    ]
