services:
  - type: web
    name: stelcity-api
    env: python
    rootDir: backend/Core
    buildCommand: "pip install -r ../requirements.txt && python manage.py migrate"
    startCommand: "gunicorn Core.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: stelcity-db
          property: connectionString

databases:
  - name: stelcity-db
    databaseName: stelcity
    user: stelcity_user